version: '3'
services:
  postgres:
    image: postgres:13.3
    container_name: mvp-postgres-services
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "product_db"
      POSTGRES_USER: "product_user"
      POSTGRES_PASSWORD: "product_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./dbroot:/root